<?php
/**
 * @var \Eloom\ThemeFrontend\Block\Adminhtml\Config\Fieldset\CookieNotice\Hint $block
 */
$helpLink = $block->escapeUrl($block->getHelpLink());
?>
<?php if ($helpLink) : ?>
    <div class="eloom-installments-notice">
        <?= $block->escapeHtml(__('Not sure what cookie notice to use? Click ')) ?>
        <a href="<?php echo $helpLink; ?>" target="_blank"><?= $block->escapeHtml(__('here')) ?></a>
        <?= $block->escapeHtml(__(' to learn more.')) ?>
    </div>
<?php endif; ?>