<?php
/**
 * @var \Eloom\ThemeFrontendCore\Block\Adminhtml\Config\Fieldset\Brand\Hint $block
 */
$helpLink = $block->escapeUrl($block->getHelpLink());
?>
<?php if ($helpLink) : ?>
    <div class="eloom-brand">
        <?= $block->escapeHtml(__('Not sure what installments to use? Click ')) ?>
        <a href="<?php echo $helpLink; ?>" target="_blank"><?= $block->escapeHtml(__('here')) ?></a>
        <?= $block->escapeHtml(__(' to learn more.')) ?>
    </div>
<?php endif; ?>