<?php
/** @var $block Eloom\ThemeFrontendCore\Block\Catalog\ImageHover */
$productId = $block->getProduct()->getId();
?>
<span data-image-hover='product-id-<?= $block->escapeHtml($productId) ?>'></span>

<script type="text/x-magento-init">
  {
      "[data-image-hover=product-id-<?= $block->escapeHtml($productId) ?>]": {
          "Eloom_ThemeFrontendCore/js/catalog/image-hover": {
            "config": <?= $block->getSerializedConfig() ?>
          }
      }
  }
</script>