<script id="infinite-scroll-status" type="text/x-magento-template">
    <div class="grid__col-sizer"></div>
    <div class="grid__gutter-sizer"></div>

    <div class="page-load-status">
        <div class="infinite-scroll-request">
            <div class="loader-spinners">
                <span class="loader-spinners__child"></span>
                <span class="loader-spinners__child"></span>
                <span class="loader-spinners__child"></span>
                <span class="loader-spinners__child"></span>
            </div>
        </div>
        <p class="infinite-scroll-last"><%- data.text %></p>
        <p class="infinite-scroll-error"><%- data.text %></p>
    </div>
</script>
<script type="text/x-magento-init">
    {
        ".products.list.items.product-items": {
            "EloomInfiniteScroll": {"config": {"hideNav": ".products.wrapper ~ .toolbar-products .pages"}, "settings": {"text": "<?= __('No more products')?>"}}
        }
    }
</script>