<?php
/** @var $block Eloom\ThemeFrontend\Block\Catalog\Product\Measure */
$measure = $block->getMeasure();
if (!$measure) {
	return;
}
$productId = $measure->getId();
?>
<a href="#" data-trigger="measures" data-eloom-measures="product-id-<?php echo $block->escapeHtml($productId)?>">
	<span><?= __('Measurement Guide')?></span>
</a>

<div id="measuresContent" data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': '<?= __('Measurement Guide')?>',
            'trigger': '[data-trigger=measures]',
            'responsive': true,
            'buttons': []
        }}">
	<div class="content">
		<h2></h2>
		<p></p>
	</div>
</div>

<script type="text/x-magento-init">
  {
      "[data-eloom-measures=product-id-<?= $block->escapeHtml($productId) ?>]": {
          "Eloom_ThemeFrontend/js/catalog/product/measure": {
            "productId": "<?= $block->escapeHtml($productId) ?>"
          }
      }
  }
</script>