<ul class="payment-logos">
	<li class="icon amex" title="American Express">
		<img src="<?php echo $this->getViewFileUrl('images/payment/flat/amex.svg'); ?>"/>
	</li>
	<li class="icon elo" title="Elo">
		<img src="<?php echo $this->getViewFileUrl('images/payment/flat/elo.svg'); ?>"/>
	</li>
	<li class="icon hipercard" title="Hipercard">
		<img src="<?php echo $this->getViewFileUrl('images/payment/flat/hipercard.svg'); ?>"/>
	</li>
	<li class="icon mastercard" title="Mastercard">
		<img src="<?php echo $this->getViewFileUrl('images/payment/flat/mastercard.svg'); ?>"/>
	</li>
	<li class="icon visa" title="Visa">
		<img src="<?php echo $this->getViewFileUrl('images/payment/flat/visa.svg'); ?>"/>
	</li>
	<li class="icon boleto" title="Boleto">
		<img src="<?php echo $this->getViewFileUrl('images/payment/boleto.svg'); ?>"/>
	</li>
</ul>