<?php
/** @var $block Eloom\ThemeFrontendCore\Block\Installments\Product */
$productId = $block->getProduct()->getId();
?>

<div id="eloom-installments-container">
</div>

<span data-badge-onsale='product-id-<?= $block->escapeHtml($productId) ?>'></span>

<script type="text/x-magento-init">
{
		"[data-badge-onsale=product-id-<?= $block->escapeHtml($productId) ?>]": {
          "Eloom_ThemeFrontendCore/js/catalog/badges/onsale/product": {}
    },
    "#eloom-installments-container": {
        "Eloom_ThemeFrontendCore/js/catalog/badges/installments/product": {
            "installments": <?= $block->getInstallmentsSerializedConfig() ?>
        }
    }
}
</script>
