<?php
/** @var $block Eloom\ThemeFrontendCore\Block\Catalog\Product\Brand */
$brand = $this->getBrand();
if (!$brand) return;
?>
<div class="brand">
    <span class="brand-title"><?php echo __('Brand') ?></span>
    <a href="<?php echo $this->getUrlBrand($brand) ?>">
        <span class="brand-name"><?php echo __($brand->getLabel()) ?></span>
			<?php if ($brand->getData('image')) : ?>
          <img class="brand"
               src="<?php echo $this->getImage($brand) ?>"
               alt="<?php echo __($brand->getTitle()) ?>"
               title="<?php echo __($brand->getTitle()) ?>"/>
			<?php endif ?>
    </a>
</div>