<?php
/** @var $block Eloom\ThemeFrontendCore\Block\Catalog\Product\ShippingEstimate */
?>
<div id="eloom-shipping-estimate" data-mage-init='{
    "scope": "shipping-estimate",
    "collapsible":{
        "openedState": "active", "collapsible": true, "active": true,
        "animate":{ "duration" :1000, "easing":"easeOutCubic"}
    }}'>
	<a href="#" data-role="title">
		<span><?= __('Calculate shipping cost')?></span>
	</a>
	<div data-role="content" data-eloom-shipping-estimate data-bind="scope:'shipping-estimate'">
		<!-- ko template: getTemplate() --><!-- /ko -->
	</div>
	<div data-role="loader" class="loader-container" style="display:none;">
		<div class="shipping-loader">
			<img src="<?php echo $this->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php __('Loading...')?>"/>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
  {
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                    "shipping-estimate": {
                        "component": "Eloom_ThemeFrontendCore/js/catalog/product/shipping-estimate"
                    }
                }
            }
        }
  }
</script>