<ul class="platform-logos">
    <li class="magento">
        <a href="//magento.com" title="<?php echo __('Magento - Plataforma de eCommerce') ?>" target="_blank" rel="nofollow">
            <img src="<?php echo $this->getViewFileUrl('images/magento.svg'); ?>"/>
        </a>
    </li>
    <li class="eloom">
        <a href="//eloom.com.br" title="<?php echo __('elOOm - eCommerce em Magento') ?>" target="_blank">
            <img src="<?php echo $this->getViewFileUrl('images/eloom-footer.svg'); ?>"/>
        </a>
    </li>
</ul>