<?php
/** @var $block Eloom\ThemeFrontend\Block\Brand\ListBrand */
$alias = 'content-'.uniqid();
$brands = $block->getBrands();
$keyword = $this->getRequest()->getParam('keyword');
?>
<?php echo $block->getChildHtml('brand_filter_by_character'); ?>
<div class="brand brand-content">
    <div class="block block-search brand-search">
        <form class="form minisearch form-search brand-form-search" id="brand_search_mini_form" action="<?php echo $this->helper->getUrlRouter() ?>" method="get">
            <div class="field search">
                <div class="control-search">
                    <input class ="keyword" type="text" name="keyword" placeholder="<?php echo __('Search a brand') ?>" value="<?php echo $block->escapeHtml($keyword) ?>"/>
                </div>
                <div class="actions">
                    <button type="submit" title="<?php echo __('Search') ?>" class="action search">
                        <span><?php echo __('Search') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
<?php if(!$brands->count()) : ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find brands matching the selection')) ?></div></div>
<?php return;?>
<?php endif;?>
    <div class="products wrapper grid products-grid">
        <ol class="products list items product-items" id="<?php echo $alias; ?>">
        <?php foreach ($brands as $brand) : ?>
            <?php $href = $this->helper->getLink($brand); ?>
            <li class="item product product-item">
                <div class="product-item-info">
                    <a class="product photo product-item-photo" href="<?= $href ?>">
                        <img src="<?= $this->helper->getMediaUrl($brand->getImage()) ?>"
                             alt="<?= $brand->getName(); ?>"/>
                    </a>
                </div>
                <div class="product details product-item-details">
                    <a class="product name product-item-name" href="<?= $href ?>"><?= $brand->getTitle(); ?></a>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>