<?php
/** @var $block Eloom\ThemeFrontend\Block\Brand\View */
$brand = $block->getBrand();
if (!$brand) return;
$helper = $this->helper;
$image = $brand->getImage();
$description = $this->getDescription();
?>
<h1 class="title"><?php echo $brand->getTitle(); ?></h1>
<?php if ($image) : ?>
<div class="brand-view">
    <div class="image">
        <img src="<?= $helper->getMediaUrl($image) ?>" alt="<?= $brand->getTitle(); ?>"/>
    </div>
	<?php endif; ?>
	<?php echo $description ? '<div class="brand-description">' . $description . '</div>' : ''; ?>
</div>
